from typing import Protocol

from app.domain.entities import (
    CategoryEntity,
    CommentEntity,
    LocationEntity,
    PostEntity,
    UserEntity,
)


class UserRepositoryPort(Protocol):
    def list(self) -> list[UserEntity]: ...
    def get(self, obj_id: int) -> UserEntity: ...
    def create(self, data: dict) -> UserEntity: ...
    def update(self, obj_id: int, data: dict) -> UserEntity: ...
    def delete(self, obj_id: int) -> None: ...
    def find_by_username(self, username: str) -> UserEntity | None: ...
    def touch_last_login(self, obj_id: int) -> UserEntity: ...


class CategoryRepositoryPort(Protocol):
    def list(self) -> list[CategoryEntity]: ...
    def get(self, obj_id: int) -> CategoryEntity: ...
    def create(self, data: dict) -> CategoryEntity: ...
    def update(self, obj_id: int, data: dict) -> CategoryEntity: ...
    def delete(self, obj_id: int) -> None: ...


class LocationRepositoryPort(Protocol):
    def list(self) -> list[LocationEntity]: ...
    def get(self, obj_id: int) -> LocationEntity: ...
    def create(self, data: dict) -> LocationEntity: ...
    def update(self, obj_id: int, data: dict) -> LocationEntity: ...
    def delete(self, obj_id: int) -> None: ...


class PostRepositoryPort(Protocol):
    def list(self) -> list[PostEntity]: ...
    def get(self, obj_id: int) -> PostEntity: ...
    def create(self, data: dict) -> PostEntity: ...
    def update(self, obj_id: int, data: dict) -> PostEntity: ...
    def delete(self, obj_id: int) -> None: ...


class CommentRepositoryPort(Protocol):
    def list(self) -> list[CommentEntity]: ...
    def get(self, obj_id: int) -> CommentEntity: ...
    def create(self, data: dict) -> CommentEntity: ...
    def update(self, obj_id: int, data: dict) -> CommentEntity: ...
    def delete(self, obj_id: int) -> None: ...
